[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
exchange_market = "Gx9Vab1RKnqq9vTBYy5rhEnfCqRwJtj1dgxseeJvmWu7"

[programs.devnet]
exchange_market = "Gx9Vab1RKnqq9vTBYy5rhEnfCqRwJtj1dgxseeJvmWu7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dev/Downloads/contract-solana/exchange-market/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
